# Generated by Django 4.2.4 on 2023-08-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eyecolor', models.CharField(max_length=8)),
                ('furcolor', models.CharField(max_length=8)),
                ('accessories', models.CharField(max_length=100)),
                ('personality', models.TextField()),
                ('experience_points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
