# Generated by Django 4.2.4 on 2023-08-12 17:45

from django.db import migrations, models
import shiba_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shiba_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiba',
            name='accessories',
        ),
        migrations.AddField(
            model_name='shiba',
            name='bow_tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiba',
            name='cane',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiba',
            name='dramatic_mustache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiba',
            name='glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiba',
            name='hair_clip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiba',
            name='muzzle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiba',
            name='top_hat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shiba',
            name='eyecolor',
            field=models.CharField(max_length=10, validators=[shiba_app.models.Shiba.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='shiba',
            name='furcolor',
            field=models.CharField(max_length=10, validators=[shiba_app.models.Shiba.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='shiba',
            name='name',
            field=models.CharField(max_length=50, validators=[shiba_app.models.Shiba.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='shiba',
            name='personality',
            field=models.TextField(validators=[shiba_app.models.Shiba.validate_alpha]),
        ),
    ]
